name: build (multiversion)
on:
  release:
    types: [created]

jobs:
    build_1_19:
        if: "!startsWith(github.event.head_commit.message, '[skip]')"
        strategy:
            matrix:
                java: [ 17 ]
        runs-on: ubuntu-latest
        steps:
            - name: steal code from repository
              uses: actions/checkout@v3

            - name: setup jdk ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ matrix.java }}

            - name: cache gradle
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/loom-cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-gradle

            - name: give gradle permission to murder github servers
              run: chmod +x ./gradlew

            - name: gradle murders github servers
              run: ./gradlew assemble -PmcVer="1.19.2"

            - name: Publish Fabric
              env:
                MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
                CURSEFORGE_TOKEN: ${{ secrets.CF_API_TOKEN }}
                MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew :fabric:build :fabric:publish :fabric:publishMods

            - name: Publish Forge
              env:
                MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
                CURSEFORGE_TOKEN: ${{ secrets.CF_API_TOKEN }}
                MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew :forge:build :forge:publish :forge:publishMods

    build_1_20:
        if: "!startsWith(github.event.head_commit.message, '[skip]')"
        strategy:
            matrix:
                java: [ 17 ]
        runs-on: ubuntu-latest
        steps:

            -   name: steal code from repository
                uses: actions/checkout@v3

            -   name: setup jdk ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}

            -   name: cache gradle
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/loom-cache
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
                    restore-keys: ${{ runner.os }}-gradle

            -   name: give gradle permission to murder github servers
                run: chmod +x ./gradlew

            -   name: gradle murders github servers
                run: ./gradlew assemble -PmcVer="1.20.1"

            - name: Publish Fabric
              env:
                MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
                CURSEFORGE_TOKEN: ${{ secrets.CF_API_TOKEN }}
                MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew :fabric:build :fabric:publish :fabric:publishMods

            - name: Publish Forge
              env:
                MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
                CURSEFORGE_TOKEN: ${{ secrets.CF_API_TOKEN }}
                MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew :forge:build :forge:publish :forge:publishMods